/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_11 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] bool
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h8: begin
        bool = a & b;
      end
      4'he: begin
        bool = a | b;
      end
      4'h6: begin
        bool = a ^ b;
      end
      4'ha: begin
        bool = a;
      end
      4'hc: begin
        bool = b;
      end
      4'h1: begin
        bool = ~a & ~b;
      end
      4'h7: begin
        bool = ~a | ~b;
      end
      4'hf: begin
        bool = 16'hffff;
      end
      default: begin
        bool = 1'h0;
      end
    endcase
  end
endmodule
