/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttons_controller_3 (
    input clk,
    input rst,
    input a,
    output reg is_pressed,
    output reg [15:0] out
  );
  
  
  
  wire [1-1:0] M_a_button_out;
  button_8 a_button (
    .clk(clk),
    .button_input(a),
    .out(M_a_button_out)
  );
  
  always @* begin
    if (M_a_button_out) begin
      out = 16'h0001;
      is_pressed = 1'h1;
    end else begin
      out = 16'h0000;
      is_pressed = 1'h0;
    end
  end
endmodule
