/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttons_controller_6 (
    input clk,
    input rst,
    input [1:0] alphabet_input,
    input is_pressed,
    output reg [4:0] out
  );
  
  
  
  wire [1-1:0] M_alphabet_pressed_out;
  button_12 alphabet_pressed (
    .clk(clk),
    .button_input(is_pressed),
    .out(M_alphabet_pressed_out)
  );
  
  always @* begin
    if (M_alphabet_pressed_out) begin
      
      case (alphabet_input)
        2'h0: begin
          out = 5'h01;
        end
        2'h1: begin
          out = 5'h02;
        end
        default: begin
          out = 1'h0;
        end
      endcase
    end
  end
endmodule
