/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_10 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [15:0] comp
  );
  
  
  
  always @* begin
    comp = 16'h0000;
    
    case (alufn[1+1-:2])
      2'h1: begin
        comp[0+0-:1] = z;
      end
      2'h2: begin
        comp[0+0-:1] = n ^ v;
      end
      2'h3: begin
        comp[0+0-:1] = z | n ^ v;
      end
    endcase
  end
endmodule
