/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mini_words_11 (
    input [10:0] selector,
    output reg [19:0] out
  );
  
  
  
  always @* begin
    
    case (selector)
      1'h1: begin
        out = 20'ha0693;
      end
      2'h2: begin
        out = 20'ha3134;
      end
      2'h3: begin
        out = 20'h625f4;
      end
      3'h4: begin
        out = 20'h631f4;
      end
      3'h5: begin
        out = 20'h82593;
      end
      3'h6: begin
        out = 20'h904b3;
      end
      3'h7: begin
        out = 20'h2cc25;
      end
      4'h8: begin
        out = 20'ha4dec;
      end
      4'h9: begin
        out = 20'h2b92c;
      end
      4'ha: begin
        out = 20'ha4830;
      end
      4'hb: begin
        out = 20'h82593;
      end
      4'hc: begin
        out = 20'h2c9f0;
      end
      4'hd: begin
        out = 20'h904ae;
      end
      4'he: begin
        out = 20'h2d032;
      end
      4'hf: begin
        out = 20'ha04b3;
      end
      5'h10: begin
        out = 20'h2d1f4;
      end
      5'h11: begin
        out = 20'h72430;
      end
      5'h12: begin
        out = 20'h2c02e;
      end
      5'h13: begin
        out = 20'h2c1f0;
      end
      5'h14: begin
        out = 20'h7d1c9;
      end
      5'h15: begin
        out = 20'h2c034;
      end
      5'h16: begin
        out = 20'h904b2;
      end
      5'h17: begin
        out = 20'h81693;
      end
      5'h18: begin
        out = 20'h2cdf0;
      end
      5'h19: begin
        out = 20'ha3df2;
      end
      5'h1a: begin
        out = 20'h6242e;
      end
      5'h1b: begin
        out = 20'h705ec;
      end
      5'h1c: begin
        out = 20'ha3d90;
      end
      5'h1d: begin
        out = 20'h84834;
      end
      5'h1e: begin
        out = 20'h904b4;
      end
      5'h1f: begin
        out = 20'h73dec;
      end
      6'h20: begin
        out = 20'h625f3;
      end
      6'h21: begin
        out = 20'ha4c30;
      end
      6'h22: begin
        out = 20'h73d2c;
      end
      6'h23: begin
        out = 20'h631f0;
      end
      6'h24: begin
        out = 20'ha49f0;
      end
      6'h25: begin
        out = 20'h904b0;
      end
      6'h26: begin
        out = 20'h2c830;
      end
      6'h27: begin
        out = 20'h09590;
      end
      6'h28: begin
        out = 20'ha4c2c;
      end
      6'h29: begin
        out = 20'h2c1f2;
      end
      6'h2a: begin
        out = 20'h904ae;
      end
      6'h2b: begin
        out = 20'h2d12c;
      end
      6'h2c: begin
        out = 20'ha3e54;
      end
      6'h2d: begin
        out = 20'ha3d90;
      end
      6'h2e: begin
        out = 20'ha4c2c;
      end
      6'h2f: begin
        out = 20'h2c132;
      end
      6'h30: begin
        out = 20'ha4cae;
      end
      6'h31: begin
        out = 20'ha4df0;
      end
      6'h32: begin
        out = 20'h72430;
      end
      6'h33: begin
        out = 20'h83d90;
      end
      6'h34: begin
        out = 20'h63133;
      end
      6'h35: begin
        out = 20'h704ac;
      end
      6'h36: begin
        out = 20'ha4830;
      end
      6'h37: begin
        out = 20'h72432;
      end
      6'h38: begin
        out = 20'h914b0;
      end
      6'h39: begin
        out = 20'h7b1f3;
      end
      6'h3a: begin
        out = 20'ha2613;
      end
      6'h3b: begin
        out = 20'h7160f;
      end
      6'h3c: begin
        out = 20'h2c9f3;
      end
      6'h3d: begin
        out = 20'h92693;
      end
      6'h3e: begin
        out = 20'h91534;
      end
      6'h3f: begin
        out = 20'ha4834;
      end
      7'h40: begin
        out = 20'h2cd32;
      end
      7'h41: begin
        out = 20'h2d032;
      end
      7'h42: begin
        out = 20'h2b930;
      end
      7'h43: begin
        out = 20'h0c030;
      end
      7'h44: begin
        out = 20'ha3133;
      end
      7'h45: begin
        out = 20'h6242e;
      end
      7'h46: begin
        out = 20'h0a641;
      end
      7'h47: begin
        out = 20'h92430;
      end
      7'h48: begin
        out = 20'h7a654;
      end
      7'h49: begin
        out = 20'h82654;
      end
      7'h4a: begin
        out = 20'h6064f;
      end
      7'h4b: begin
        out = 20'ha4cb2;
      end
      7'h4c: begin
        out = 20'h2cc25;
      end
      7'h4d: begin
        out = 20'ha49f3;
      end
      7'h4e: begin
        out = 20'h9cdf4;
      end
      7'h4f: begin
        out = 20'h80654;
      end
      7'h50: begin
        out = 20'h09641;
      end
      7'h51: begin
        out = 20'ha4cb2;
      end
      7'h52: begin
        out = 20'h2c032;
      end
      7'h53: begin
        out = 20'ha49f4;
      end
      7'h54: begin
        out = 20'h2d030;
      end
      7'h55: begin
        out = 20'h2cdee;
      end
      7'h56: begin
        out = 20'h2c1f2;
      end
      7'h57: begin
        out = 20'h73dee;
      end
      7'h58: begin
        out = 20'h83e93;
      end
      7'h59: begin
        out = 20'h625f3;
      end
      7'h5a: begin
        out = 20'h2b130;
      end
      7'h5b: begin
        out = 20'h2b134;
      end
      7'h5c: begin
        out = 20'h62434;
      end
      7'h5d: begin
        out = 20'ha4830;
      end
      7'h5e: begin
        out = 20'h2b9f4;
      end
      7'h5f: begin
        out = 20'h2c032;
      end
      7'h60: begin
        out = 20'h724b2;
      end
      7'h61: begin
        out = 20'h2d133;
      end
      7'h62: begin
        out = 20'h83e81;
      end
      7'h63: begin
        out = 20'h2b9ec;
      end
      7'h64: begin
        out = 20'ha49f3;
      end
      7'h65: begin
        out = 20'h914b0;
      end
      7'h66: begin
        out = 20'h2d133;
      end
      7'h67: begin
        out = 20'h63df0;
      end
      7'h68: begin
        out = 20'h905f3;
      end
      7'h69: begin
        out = 20'h804ac;
      end
      7'h6a: begin
        out = 20'h2d02c;
      end
      7'h6b: begin
        out = 20'ha4df0;
      end
      7'h6c: begin
        out = 20'h804ac;
      end
      7'h6d: begin
        out = 20'h2b92e;
      end
      7'h6e: begin
        out = 20'h2cdf2;
      end
      7'h6f: begin
        out = 20'h631ec;
      end
      7'h70: begin
        out = 20'h2b9f4;
      end
      7'h71: begin
        out = 20'h2d132;
      end
      7'h72: begin
        out = 20'ha3d93;
      end
      7'h73: begin
        out = 20'ha4cae;
      end
      7'h74: begin
        out = 20'ha30b0;
      end
      7'h75: begin
        out = 20'h2c934;
      end
      7'h76: begin
        out = 20'ha4c25;
      end
      7'h77: begin
        out = 20'h70613;
      end
      7'h78: begin
        out = 20'h914b3;
      end
      7'h79: begin
        out = 20'ha4c30;
      end
      7'h7a: begin
        out = 20'h2b92c;
      end
      7'h7b: begin
        out = 20'h73df3;
      end
      7'h7c: begin
        out = 20'h92693;
      end
      7'h7d: begin
        out = 20'ha04b3;
      end
      7'h7e: begin
        out = 20'h705ec;
      end
      7'h7f: begin
        out = 20'h2d02c;
      end
      8'h80: begin
        out = 20'h81693;
      end
      8'h81: begin
        out = 20'h70613;
      end
      8'h82: begin
        out = 20'h814b3;
      end
      8'h83: begin
        out = 20'ha4d2c;
      end
      8'h84: begin
        out = 20'ha3d93;
      end
      8'h85: begin
        out = 20'h72613;
      end
      8'h86: begin
        out = 20'h2b9ee;
      end
      8'h87: begin
        out = 20'h62432;
      end
      8'h88: begin
        out = 20'ha4830;
      end
      8'h89: begin
        out = 20'h2b030;
      end
      8'h8a: begin
        out = 20'h9ccac;
      end
      8'h8b: begin
        out = 20'h904ae;
      end
      8'h8c: begin
        out = 20'h904ae;
      end
      8'h8d: begin
        out = 20'h805d3;
      end
      8'h8e: begin
        out = 20'h805f3;
      end
      8'h8f: begin
        out = 20'h29654;
      end
      8'h90: begin
        out = 20'h9d1ec;
      end
      8'h91: begin
        out = 20'h9cc30;
      end
      8'h92: begin
        out = 20'ha4cac;
      end
      8'h93: begin
        out = 20'h83dec;
      end
      8'h94: begin
        out = 20'h905f2;
      end
      8'h95: begin
        out = 20'ha4cb0;
      end
      8'h96: begin
        out = 20'h83e93;
      end
      8'h97: begin
        out = 20'h7b1f3;
      end
      8'h98: begin
        out = 20'h7b1f0;
      end
      8'h99: begin
        out = 20'h9cdec;
      end
      8'h9a: begin
        out = 20'h2c1ee;
      end
      8'h9b: begin
        out = 20'ha4c2c;
      end
      8'h9c: begin
        out = 20'h2b1f3;
      end
      8'h9d: begin
        out = 20'h904b2;
      end
      8'h9e: begin
        out = 20'h0c830;
      end
      8'h9f: begin
        out = 20'h83e50;
      end
      8'ha0: begin
        out = 20'ha3df3;
      end
      8'ha1: begin
        out = 20'ha3df2;
      end
      8'ha2: begin
        out = 20'ha2593;
      end
      8'ha3: begin
        out = 20'h2b930;
      end
      8'ha4: begin
        out = 20'h2cd85;
      end
      8'ha5: begin
        out = 20'h2d1ee;
      end
      8'ha6: begin
        out = 20'h63034;
      end
      8'ha7: begin
        out = 20'h72613;
      end
      8'ha8: begin
        out = 20'h80593;
      end
      8'ha9: begin
        out = 20'ha2593;
      end
      8'haa: begin
        out = 20'h804b2;
      end
      8'hab: begin
        out = 20'h2b030;
      end
      8'hac: begin
        out = 20'h724b2;
      end
      8'had: begin
        out = 20'ha3e13;
      end
      8'hae: begin
        out = 20'h2c9f3;
      end
      8'haf: begin
        out = 20'h2c9ec;
      end
      8'hb0: begin
        out = 20'h2b1f0;
      end
      8'hb1: begin
        out = 20'ha04b0;
      end
      8'hb2: begin
        out = 20'h631f2;
      end
      8'hb3: begin
        out = 20'h630b4;
      end
      8'hb4: begin
        out = 20'h63df4;
      end
      8'hb5: begin
        out = 20'h7160f;
      end
      8'hb6: begin
        out = 20'h62433;
      end
      8'hb7: begin
        out = 20'h2c034;
      end
      8'hb8: begin
        out = 20'h92430;
      end
      8'hb9: begin
        out = 20'h2b132;
      end
      8'hba: begin
        out = 20'ha30b0;
      end
      8'hbb: begin
        out = 20'h0d130;
      end
      8'hbc: begin
        out = 20'h631f4;
      end
      8'hbd: begin
        out = 20'h2d1f2;
      end
      8'hbe: begin
        out = 20'h614b2;
      end
      8'hbf: begin
        out = 20'h4c833;
      end
      8'hc0: begin
        out = 20'h63134;
      end
      8'hc1: begin
        out = 20'h630b3;
      end
      8'hc2: begin
        out = 20'ha15f0;
      end
      8'hc3: begin
        out = 20'ha4d2c;
      end
      8'hc4: begin
        out = 20'h73df3;
      end
      8'hc5: begin
        out = 20'ha3033;
      end
      8'hc6: begin
        out = 20'h749f4;
      end
      8'hc7: begin
        out = 20'h81650;
      end
      8'hc8: begin
        out = 20'h73e49;
      end
      8'hc9: begin
        out = 20'h814b0;
      end
      8'hca: begin
        out = 20'h2c832;
      end
      8'hcb: begin
        out = 20'ha3832;
      end
      8'hcc: begin
        out = 20'h704ac;
      end
      8'hcd: begin
        out = 20'h748b4;
      end
      8'hce: begin
        out = 20'h2b830;
      end
      8'hcf: begin
        out = 20'h98581;
      end
      8'hd0: begin
        out = 20'h9d02f;
      end
      8'hd1: begin
        out = 20'h74825;
      end
      8'hd2: begin
        out = 20'h90693;
      end
      8'hd3: begin
        out = 20'h90693;
      end
      8'hd4: begin
        out = 20'h604b3;
      end
      8'hd5: begin
        out = 20'h625f2;
      end
      8'hd6: begin
        out = 20'h2d1f4;
      end
      8'hd7: begin
        out = 20'h9ccac;
      end
      8'hd8: begin
        out = 20'h7d1cf;
      end
      8'hd9: begin
        out = 20'h2cdee;
      end
      8'hda: begin
        out = 20'h614b0;
      end
      8'hdb: begin
        out = 20'h7b133;
      end
      8'hdc: begin
        out = 20'h9a649;
      end
      8'hdd: begin
        out = 20'ha3830;
      end
      8'hde: begin
        out = 20'ha3e13;
      end
      8'hdf: begin
        out = 20'ha38b2;
      end
      8'he0: begin
        out = 20'h9cdf4;
      end
      8'he1: begin
        out = 20'h630b3;
      end
      8'he2: begin
        out = 20'h631f2;
      end
      8'he3: begin
        out = 20'h9052c;
      end
      8'he4: begin
        out = 20'h2cd32;
      end
      8'he5: begin
        out = 20'h90613;
      end
      8'he6: begin
        out = 20'h2b130;
      end
      8'he7: begin
        out = 20'h614b0;
      end
      8'he8: begin
        out = 20'h2b033;
      end
      8'he9: begin
        out = 20'h70590;
      end
      8'hea: begin
        out = 20'h9242c;
      end
      8'heb: begin
        out = 20'h725ec;
      end
      8'hec: begin
        out = 20'h93df0;
      end
      8'hed: begin
        out = 20'h2cdf0;
      end
      8'hee: begin
        out = 20'h604b2;
      end
      8'hef: begin
        out = 20'h904b4;
      end
      8'hf0: begin
        out = 20'h91530;
      end
      8'hf1: begin
        out = 20'h63df0;
      end
      8'hf2: begin
        out = 20'h80654;
      end
      8'hf3: begin
        out = 20'h83dec;
      end
      8'hf4: begin
        out = 20'h2b034;
      end
      8'hf5: begin
        out = 20'h2cdec;
      end
      8'hf6: begin
        out = 20'ha4c30;
      end
      8'hf7: begin
        out = 20'ha4834;
      end
      8'hf8: begin
        out = 20'ha4c30;
      end
      8'hf9: begin
        out = 20'h70590;
      end
      8'hfa: begin
        out = 20'h62434;
      end
      8'hfb: begin
        out = 20'h814b0;
      end
      8'hfc: begin
        out = 20'h4d1c1;
      end
      8'hfd: begin
        out = 20'h62432;
      end
      8'hfe: begin
        out = 20'h805d3;
      end
      8'hff: begin
        out = 20'ha04ae;
      end
      9'h100: begin
        out = 20'ha3e54;
      end
      9'h101: begin
        out = 20'h81650;
      end
      9'h102: begin
        out = 20'h2d1ee;
      end
      9'h103: begin
        out = 20'h80593;
      end
      9'h104: begin
        out = 20'h714b4;
      end
      9'h105: begin
        out = 20'h904b2;
      end
      9'h106: begin
        out = 20'h9b8ac;
      end
      9'h107: begin
        out = 20'ha3134;
      end
      9'h108: begin
        out = 20'h2c130;
      end
      9'h109: begin
        out = 20'h614b2;
      end
      9'h10a: begin
        out = 20'ha3830;
      end
      9'h10b: begin
        out = 20'ha3934;
      end
      9'h10c: begin
        out = 20'h73cae;
      end
      9'h10d: begin
        out = 20'ha4cb4;
      end
      9'h10e: begin
        out = 20'h7160f;
      end
      9'h10f: begin
        out = 20'h2c130;
      end
      9'h110: begin
        out = 20'h604b3;
      end
      9'h111: begin
        out = 20'h72432;
      end
      9'h112: begin
        out = 20'h83e50;
      end
      9'h113: begin
        out = 20'h9c1ef;
      end
      9'h114: begin
        out = 20'h63130;
      end
      9'h115: begin
        out = 20'h7cd81;
      end
      9'h116: begin
        out = 20'h82654;
      end
      9'h117: begin
        out = 20'h63134;
      end
      9'h118: begin
        out = 20'h9cc30;
      end
      9'h119: begin
        out = 20'h2b1f2;
      end
      9'h11a: begin
        out = 20'ha38b2;
      end
      9'h11b: begin
        out = 20'h6064f;
      end
      9'h11c: begin
        out = 20'ha3934;
      end
      9'h11d: begin
        out = 20'h805d3;
      end
      9'h11e: begin
        out = 20'ha4cb4;
      end
      9'h11f: begin
        out = 20'h73e49;
      end
      9'h120: begin
        out = 20'ha3dec;
      end
      9'h121: begin
        out = 20'h631f0;
      end
      9'h122: begin
        out = 20'ha4032;
      end
      9'h123: begin
        out = 20'h604b2;
      end
      9'h124: begin
        out = 20'h2b82c;
      end
      9'h125: begin
        out = 20'h2b833;
      end
      9'h126: begin
        out = 20'h905f2;
      end
      9'h127: begin
        out = 20'ha3dec;
      end
      9'h128: begin
        out = 20'h62430;
      end
      9'h129: begin
        out = 20'ha3d32;
      end
      9'h12a: begin
        out = 20'h90693;
      end
      9'h12b: begin
        out = 20'h2b1f3;
      end
      9'h12c: begin
        out = 20'ha38b4;
      end
      9'h12d: begin
        out = 20'ha0593;
      end
      9'h12e: begin
        out = 20'h2c1ec;
      end
      9'h12f: begin
        out = 20'ha2613;
      end
      9'h130: begin
        out = 20'h825d3;
      end
      9'h131: begin
        out = 20'h2c9f0;
      end
      default: begin
        out = 20'h9d4e1;
      end
    endcase
  end
endmodule
