/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module panel_controller_4 (
    input clk,
    input rst,
    input clear,
    output reg is_pressed,
    output reg [4:0] out
  );
  
  
  
  wire [1-1:0] M_clear__out;
  button_11 clear_ (
    .clk(clk),
    .button_input(clear),
    .out(M_clear__out)
  );
  
  always @* begin
    if (M_clear__out) begin
      out = 5'h1f;
      is_pressed = 1'h1;
    end else begin
      out = 5'h00;
      is_pressed = 1'h0;
    end
  end
endmodule
