/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module words_10 (
    input [10:0] selector,
    output reg [19:0] out
  );
  
  
  
  localparam INPUTS = 20'h11833;
  
  always @* begin
    out = INPUTS;
  end
endmodule
