/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    input usb_rx,
    output reg outled,
    output reg usb_tx
  );
  
  
  
  reg rst;
  
  wire [5-1:0] M_led_strip_pixel;
  wire [1-1:0] M_led_strip_led;
  reg [1-1:0] M_led_strip_update;
  reg [24-1:0] M_led_strip_color;
  led_strip_writer_1 led_strip (
    .clk(clk),
    .rst(rst),
    .update(M_led_strip_update),
    .color(M_led_strip_color),
    .pixel(M_led_strip_pixel),
    .led(M_led_strip_led)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [600-1:0] M_letters_config_out;
  reg [2-1:0] M_letters_config_selector;
  green_alphabets_3 letters_config (
    .selector(M_letters_config_selector),
    .out(M_letters_config_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    M_led_strip_update = 1'h1;
    M_letters_config_selector = 1'h1;
    M_led_strip_color = M_letters_config_out[(M_led_strip_pixel)*24+23-:24];
    outled = M_led_strip_led;
  end
endmodule
