/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttons_controller_2 (
    input clk,
    input rst,
    input aIn,
    output reg is_pressed,
    output reg out
  );
  
  
  
  wire [1-1:0] M_a_out;
  button_4 a (
    .clk(clk),
    .button_input(aIn),
    .out(M_a_out)
  );
  
  always @* begin
    
    case (M_a_out)
      1'h1: begin
        out = M_a_out;
        is_pressed = 1'h1;
      end
      default: begin
        out = 1'h0;
        is_pressed = 1'h0;
      end
    endcase
  end
endmodule
