/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttons_controller_3 (
    input clk,
    input rst,
    input a,
    input b,
    input e,
    input r,
    output reg is_pressed,
    output reg [15:0] out
  );
  
  
  
  wire [1-1:0] M_a__out;
  button_10 a_ (
    .clk(clk),
    .button_input(a),
    .out(M_a__out)
  );
  wire [1-1:0] M_b__out;
  button_10 b_ (
    .clk(clk),
    .button_input(b),
    .out(M_b__out)
  );
  wire [1-1:0] M_e__out;
  button_10 e_ (
    .clk(clk),
    .button_input(e),
    .out(M_e__out)
  );
  wire [1-1:0] M_r__out;
  button_10 r_ (
    .clk(clk),
    .button_input(r),
    .out(M_r__out)
  );
  
  always @* begin
    if (M_a__out) begin
      out = 5'h01;
      is_pressed = 1'h1;
    end else begin
      if (M_e__out) begin
        out = 3'h5;
        is_pressed = 1'h1;
      end else begin
        if (M_b__out) begin
          out = 5'h02;
          is_pressed = 1'h1;
        end else begin
          if (M_r__out) begin
            out = 5'h12;
            is_pressed = 1'h1;
          end else begin
            out = 16'h0000;
            is_pressed = 1'h0;
          end
        end
      end
    end
  end
endmodule
