/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module letters_3 (
    input [4:0] selector,
    output reg [599:0] out
  );
  
  
  
  localparam INPUTS = 1200'h000000000000001100000000000000000000001100000000001100000000001100000000000000000000001100001100001100001100001100001100001100000000000000000000001100001100001100001100001100000000001100000000000000000000001100001100001100001100001100000000001100000000000000000000001100001100001100001100001100000000;
  
  always @* begin
    out = INPUTS[(selector)*600+599-:600];
  end
endmodule
