/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mini_words_10 (
    input [10:0] selector,
    output reg [19:0] out
  );
  
  
  
  always @* begin
    
    case (selector)
      1'h1: begin
        out = 20'h9d034;
      end
      2'h2: begin
        out = 20'ha2594;
      end
      2'h3: begin
        out = 20'ha3d2c;
      end
      3'h4: begin
        out = 20'ha3d8c;
      end
      3'h5: begin
        out = 20'h9b130;
      end
      3'h6: begin
        out = 20'h99432;
      end
      3'h7: begin
        out = 20'h28665;
      end
      4'h8: begin
        out = 20'h63e74;
      end
      4'h9: begin
        out = 20'h625c5;
      end
      4'ha: begin
        out = 20'h80654;
      end
      4'hb: begin
        out = 20'h9b130;
      end
      4'hc: begin
        out = 20'h83e45;
      end
      4'hd: begin
        out = 20'h71432;
      end
      4'he: begin
        out = 20'h90685;
      end
      4'hf: begin
        out = 20'h99434;
      end
      5'h10: begin
        out = 20'ha3e85;
      end
      5'h11: begin
        out = 20'h8052e;
      end
      5'h12: begin
        out = 20'h70605;
      end
      5'h13: begin
        out = 20'h83e05;
      end
      5'h14: begin
        out = 20'h4ba8f;
      end
      5'h15: begin
        out = 20'ha0605;
      end
      5'h16: begin
        out = 20'h91432;
      end
      5'h17: begin
        out = 20'h9d0b0;
      end
      5'h18: begin
        out = 20'h83e65;
      end
      5'h19: begin
        out = 20'h93df4;
      end
      5'h1a: begin
        out = 20'h7052c;
      end
      5'h1b: begin
        out = 20'h63c2e;
      end
      5'h1c: begin
        out = 20'h831f4;
      end
      5'h1d: begin
        out = 20'ha0650;
      end
      5'h1e: begin
        out = 20'ha1432;
      end
      5'h1f: begin
        out = 20'h63dee;
      end
      6'h20: begin
        out = 20'h9bd2c;
      end
      6'h21: begin
        out = 20'h80674;
      end
      6'h22: begin
        out = 20'h625ee;
      end
      6'h23: begin
        out = 20'h83d8c;
      end
      6'h24: begin
        out = 20'h83e54;
      end
      6'h25: begin
        out = 20'h81432;
      end
      6'h26: begin
        out = 20'h80645;
      end
      6'h27: begin
        out = 20'h830a1;
      end
      6'h28: begin
        out = 20'h60674;
      end
      6'h29: begin
        out = 20'h93e05;
      end
      6'h2a: begin
        out = 20'h71432;
      end
      6'h2b: begin
        out = 20'h62685;
      end
      6'h2c: begin
        out = 20'ha49f4;
      end
      6'h2d: begin
        out = 20'h831f4;
      end
      6'h2e: begin
        out = 20'h60674;
      end
      6'h2f: begin
        out = 20'h92605;
      end
      6'h30: begin
        out = 20'h71674;
      end
      6'h31: begin
        out = 20'h83e74;
      end
      6'h32: begin
        out = 20'h8052e;
      end
      6'h33: begin
        out = 20'h831f0;
      end
      6'h34: begin
        out = 20'h9a58c;
      end
      6'h35: begin
        out = 20'h6142e;
      end
      6'h36: begin
        out = 20'h80654;
      end
      6'h37: begin
        out = 20'h9052e;
      end
      6'h38: begin
        out = 20'h814b2;
      end
      6'h39: begin
        out = 20'h9bd8f;
      end
      6'h3a: begin
        out = 20'h9c134;
      end
      6'h3b: begin
        out = 20'h7c0ae;
      end
      6'h3c: begin
        out = 20'h9be45;
      end
      6'h3d: begin
        out = 20'h9d132;
      end
      6'h3e: begin
        out = 20'ha24b2;
      end
      6'h3f: begin
        out = 20'ha0654;
      end
      7'h40: begin
        out = 20'h92665;
      end
      7'h41: begin
        out = 20'h90685;
      end
      7'h42: begin
        out = 20'h825c5;
      end
      7'h43: begin
        out = 20'h80601;
      end
      7'h44: begin
        out = 20'h9a594;
      end
      7'h45: begin
        out = 20'h7052c;
      end
      7'h46: begin
        out = 20'h0c921;
      end
      7'h47: begin
        out = 20'h80532;
      end
      7'h48: begin
        out = 20'ha492f;
      end
      7'h49: begin
        out = 20'ha4930;
      end
      7'h4a: begin
        out = 20'h7c82c;
      end
      7'h4b: begin
        out = 20'h91674;
      end
      7'h4c: begin
        out = 20'h28665;
      end
      7'h4d: begin
        out = 20'h9be54;
      end
      7'h4e: begin
        out = 20'ha3e73;
      end
      7'h4f: begin
        out = 20'ha4830;
      end
      7'h50: begin
        out = 20'h0c8a1;
      end
      7'h51: begin
        out = 20'h91674;
      end
      7'h52: begin
        out = 20'h90605;
      end
      7'h53: begin
        out = 20'ha3e54;
      end
      7'h54: begin
        out = 20'h80685;
      end
      7'h55: begin
        out = 20'h73e65;
      end
      7'h56: begin
        out = 20'h93e05;
      end
      7'h57: begin
        out = 20'h73dee;
      end
      7'h58: begin
        out = 20'h9d1f0;
      end
      7'h59: begin
        out = 20'h9bd2c;
      end
      7'h5a: begin
        out = 20'h82585;
      end
      7'h5b: begin
        out = 20'ha2585;
      end
      7'h5c: begin
        out = 20'ha052c;
      end
      7'h5d: begin
        out = 20'h80654;
      end
      7'h5e: begin
        out = 20'ha3dc5;
      end
      7'h5f: begin
        out = 20'h90605;
      end
      7'h60: begin
        out = 20'h9152e;
      end
      7'h61: begin
        out = 20'h9a685;
      end
      7'h62: begin
        out = 20'h0d1f0;
      end
      7'h63: begin
        out = 20'h63dc5;
      end
      7'h64: begin
        out = 20'h9be54;
      end
      7'h65: begin
        out = 20'h814b2;
      end
      7'h66: begin
        out = 20'h9a685;
      end
      7'h67: begin
        out = 20'h83dec;
      end
      7'h68: begin
        out = 20'h9bc32;
      end
      7'h69: begin
        out = 20'h61430;
      end
      7'h6a: begin
        out = 20'h60685;
      end
      7'h6b: begin
        out = 20'h83e74;
      end
      7'h6c: begin
        out = 20'h61430;
      end
      7'h6d: begin
        out = 20'h725c5;
      end
      7'h6e: begin
        out = 20'h93e65;
      end
      7'h6f: begin
        out = 20'h63d8c;
      end
      7'h70: begin
        out = 20'ha3dc5;
      end
      7'h71: begin
        out = 20'h92685;
      end
      7'h72: begin
        out = 20'h9b1f4;
      end
      7'h73: begin
        out = 20'h71674;
      end
      7'h74: begin
        out = 20'h81594;
      end
      7'h75: begin
        out = 20'ha2645;
      end
      7'h76: begin
        out = 20'h28674;
      end
      7'h77: begin
        out = 20'h9c02e;
      end
      7'h78: begin
        out = 20'h994b2;
      end
      7'h79: begin
        out = 20'h80674;
      end
      7'h7a: begin
        out = 20'h625c5;
      end
      7'h7b: begin
        out = 20'h9bdee;
      end
      7'h7c: begin
        out = 20'h9d132;
      end
      7'h7d: begin
        out = 20'h99434;
      end
      7'h7e: begin
        out = 20'h63c2e;
      end
      7'h7f: begin
        out = 20'h60685;
      end
      8'h80: begin
        out = 20'h9d0b0;
      end
      8'h81: begin
        out = 20'h9c02e;
      end
      8'h82: begin
        out = 20'h994b0;
      end
      8'h83: begin
        out = 20'h62674;
      end
      8'h84: begin
        out = 20'h9b1f4;
      end
      8'h85: begin
        out = 20'h9c12e;
      end
      8'h86: begin
        out = 20'h73dc5;
      end
      8'h87: begin
        out = 20'h9052c;
      end
      8'h88: begin
        out = 20'h80654;
      end
      8'h89: begin
        out = 20'h80585;
      end
      8'h8a: begin
        out = 20'h61673;
      end
      8'h8b: begin
        out = 20'h71432;
      end
      8'h8c: begin
        out = 20'h71432;
      end
      8'h8d: begin
        out = 20'h9b830;
      end
      8'h8e: begin
        out = 20'h9bc30;
      end
      8'h8f: begin
        out = 20'ha48a5;
      end
      8'h90: begin
        out = 20'h63e93;
      end
      8'h91: begin
        out = 20'h80673;
      end
      8'h92: begin
        out = 20'h61674;
      end
      8'h93: begin
        out = 20'h63df0;
      end
      8'h94: begin
        out = 20'h93c32;
      end
      8'h95: begin
        out = 20'h81674;
      end
      8'h96: begin
        out = 20'h9d1f0;
      end
      8'h97: begin
        out = 20'h9bd8f;
      end
      8'h98: begin
        out = 20'h83d8f;
      end
      8'h99: begin
        out = 20'h63e73;
      end
      8'h9a: begin
        out = 20'h73e05;
      end
      8'h9b: begin
        out = 20'h60674;
      end
      8'h9c: begin
        out = 20'h9bd85;
      end
      8'h9d: begin
        out = 20'h91432;
      end
      8'h9e: begin
        out = 20'h80641;
      end
      8'h9f: begin
        out = 20'h849f0;
      end
      8'ha0: begin
        out = 20'h9bdf4;
      end
      8'ha1: begin
        out = 20'h93df4;
      end
      8'ha2: begin
        out = 20'h9b134;
      end
      8'ha3: begin
        out = 20'h825c5;
      end
      8'ha4: begin
        out = 20'h2b265;
      end
      8'ha5: begin
        out = 20'h73e85;
      end
      8'ha6: begin
        out = 20'ha058c;
      end
      8'ha7: begin
        out = 20'h9c12e;
      end
      8'ha8: begin
        out = 20'h9b030;
      end
      8'ha9: begin
        out = 20'h9b134;
      end
      8'haa: begin
        out = 20'h91430;
      end
      8'hab: begin
        out = 20'h80585;
      end
      8'hac: begin
        out = 20'h9152e;
      end
      8'had: begin
        out = 20'h9c1f4;
      end
      8'hae: begin
        out = 20'h9be45;
      end
      8'haf: begin
        out = 20'h63e45;
      end
      8'hb0: begin
        out = 20'h83d85;
      end
      8'hb1: begin
        out = 20'h81434;
      end
      8'hb2: begin
        out = 20'h93d8c;
      end
      8'hb3: begin
        out = 20'ha158c;
      end
      8'hb4: begin
        out = 20'ha3dec;
      end
      8'hb5: begin
        out = 20'h7c0ae;
      end
      8'hb6: begin
        out = 20'h9852c;
      end
      8'hb7: begin
        out = 20'ha0605;
      end
      8'hb8: begin
        out = 20'h80532;
      end
      8'hb9: begin
        out = 20'h92585;
      end
      8'hba: begin
        out = 20'h81594;
      end
      8'hbb: begin
        out = 20'h82681;
      end
      8'hbc: begin
        out = 20'ha3d8c;
      end
      8'hbd: begin
        out = 20'h93e85;
      end
      8'hbe: begin
        out = 20'h914ac;
      end
      8'hbf: begin
        out = 20'h98649;
      end
      8'hc0: begin
        out = 20'ha258c;
      end
      8'hc1: begin
        out = 20'h9958c;
      end
      8'hc2: begin
        out = 20'h83cb4;
      end
      8'hc3: begin
        out = 20'h62674;
      end
      8'hc4: begin
        out = 20'h9bdee;
      end
      8'hc5: begin
        out = 20'h98594;
      end
      8'hc6: begin
        out = 20'ha3e4e;
      end
      8'hc7: begin
        out = 20'h848b0;
      end
      8'hc8: begin
        out = 20'h4c9ee;
      end
      8'hc9: begin
        out = 20'h814b0;
      end
      8'hca: begin
        out = 20'h90645;
      end
      8'hcb: begin
        out = 20'h905d4;
      end
      8'hcc: begin
        out = 20'h6142e;
      end
      8'hcd: begin
        out = 20'ha164e;
      end
      8'hce: begin
        out = 20'h805c5;
      end
      8'hcf: begin
        out = 20'h0b033;
      end
      8'hd0: begin
        out = 20'h78693;
      end
      8'hd1: begin
        out = 20'h2864e;
      end
      8'hd2: begin
        out = 20'h9d032;
      end
      8'hd3: begin
        out = 20'h9d032;
      end
      8'hd4: begin
        out = 20'h9942c;
      end
      8'hd5: begin
        out = 20'h93d2c;
      end
      8'hd6: begin
        out = 20'ha3e85;
      end
      8'hd7: begin
        out = 20'h61673;
      end
      8'hd8: begin
        out = 20'h7ba8f;
      end
      8'hd9: begin
        out = 20'h73e65;
      end
      8'hda: begin
        out = 20'h814ac;
      end
      8'hdb: begin
        out = 20'h9a58f;
      end
      8'hdc: begin
        out = 20'h4c933;
      end
      8'hdd: begin
        out = 20'h805d4;
      end
      8'hde: begin
        out = 20'h9c1f4;
      end
      8'hdf: begin
        out = 20'h915d4;
      end
      8'he0: begin
        out = 20'ha3e73;
      end
      8'he1: begin
        out = 20'h9958c;
      end
      8'he2: begin
        out = 20'h93d8c;
      end
      8'he3: begin
        out = 20'h62432;
      end
      8'he4: begin
        out = 20'h92665;
      end
      8'he5: begin
        out = 20'h9c032;
      end
      8'he6: begin
        out = 20'h82585;
      end
      8'he7: begin
        out = 20'h814ac;
      end
      8'he8: begin
        out = 20'h98585;
      end
      8'he9: begin
        out = 20'h8302e;
      end
      8'hea: begin
        out = 20'h60532;
      end
      8'heb: begin
        out = 20'h63d2e;
      end
      8'hec: begin
        out = 20'h83df2;
      end
      8'hed: begin
        out = 20'h83e65;
      end
      8'hee: begin
        out = 20'h9142c;
      end
      8'hef: begin
        out = 20'ha1432;
      end
      8'hf0: begin
        out = 20'h824b2;
      end
      8'hf1: begin
        out = 20'h83dec;
      end
      8'hf2: begin
        out = 20'ha4830;
      end
      8'hf3: begin
        out = 20'h63df0;
      end
      8'hf4: begin
        out = 20'ha0585;
      end
      8'hf5: begin
        out = 20'h63e65;
      end
      8'hf6: begin
        out = 20'h80674;
      end
      8'hf7: begin
        out = 20'ha0654;
      end
      8'hf8: begin
        out = 20'h80674;
      end
      8'hf9: begin
        out = 20'h8302e;
      end
      8'hfa: begin
        out = 20'ha052c;
      end
      8'hfb: begin
        out = 20'h814b0;
      end
      8'hfc: begin
        out = 20'h0ba89;
      end
      8'hfd: begin
        out = 20'h9052c;
      end
      8'hfe: begin
        out = 20'h9b830;
      end
      8'hff: begin
        out = 20'h71434;
      end
      9'h100: begin
        out = 20'ha49f4;
      end
      9'h101: begin
        out = 20'h848b0;
      end
      9'h102: begin
        out = 20'h73e85;
      end
      9'h103: begin
        out = 20'h9b030;
      end
      9'h104: begin
        out = 20'ha14ae;
      end
      9'h105: begin
        out = 20'h91432;
      end
      9'h106: begin
        out = 20'h615d3;
      end
      9'h107: begin
        out = 20'ha2594;
      end
      9'h108: begin
        out = 20'h82605;
      end
      9'h109: begin
        out = 20'h914ac;
      end
      9'h10a: begin
        out = 20'h805d4;
      end
      9'h10b: begin
        out = 20'ha25d4;
      end
      9'h10c: begin
        out = 20'h715ee;
      end
      9'h10d: begin
        out = 20'ha1674;
      end
      9'h10e: begin
        out = 20'h7c0ae;
      end
      9'h10f: begin
        out = 20'h82605;
      end
      9'h110: begin
        out = 20'h9942c;
      end
      9'h111: begin
        out = 20'h9052e;
      end
      9'h112: begin
        out = 20'h849f0;
      end
      9'h113: begin
        out = 20'h7be13;
      end
      9'h114: begin
        out = 20'h8258c;
      end
      9'h115: begin
        out = 20'h0b26f;
      end
      9'h116: begin
        out = 20'ha4930;
      end
      9'h117: begin
        out = 20'ha258c;
      end
      9'h118: begin
        out = 20'h80673;
      end
      9'h119: begin
        out = 20'h93d85;
      end
      9'h11a: begin
        out = 20'h915d4;
      end
      9'h11b: begin
        out = 20'h7c82c;
      end
      9'h11c: begin
        out = 20'ha25d4;
      end
      9'h11d: begin
        out = 20'h9b830;
      end
      9'h11e: begin
        out = 20'ha1674;
      end
      9'h11f: begin
        out = 20'h4c9ee;
      end
      9'h120: begin
        out = 20'h63df4;
      end
      9'h121: begin
        out = 20'h83d8c;
      end
      9'h122: begin
        out = 20'h90614;
      end
      9'h123: begin
        out = 20'h9142c;
      end
      9'h124: begin
        out = 20'h605c5;
      end
      9'h125: begin
        out = 20'h985c5;
      end
      9'h126: begin
        out = 20'h93c32;
      end
      9'h127: begin
        out = 20'h63df4;
      end
      9'h128: begin
        out = 20'h8052c;
      end
      9'h129: begin
        out = 20'h925f4;
      end
      9'h12a: begin
        out = 20'h9d032;
      end
      9'h12b: begin
        out = 20'h9bd85;
      end
      9'h12c: begin
        out = 20'ha15d4;
      end
      9'h12d: begin
        out = 20'h9b034;
      end
      9'h12e: begin
        out = 20'h63e05;
      end
      9'h12f: begin
        out = 20'h9c134;
      end
      9'h130: begin
        out = 20'h9b930;
      end
      9'h131: begin
        out = 20'h83e45;
      end
      default: begin
        out = 20'h09eb3;
      end
    endcase
  end
endmodule
