set_property SRC_FILE_INFO {cfile:{C:/Program Files/Alchitry/Alchitry Labs/library/components/au.xdc} rfile:{../../../../../../../../../../../../../../Program Files/Alchitry/Alchitry Labs/library/components/au.xdc} id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Loan/Documents/GitHub/wordle/wordle4/work/constraint/alchitry.xdc rfile:../../../../../../../constraint/alchitry.xdc id:2} [current_design]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_0 -waveform {0.000 5.000} [get_ports clk]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports outled1]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports outled2]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_rx]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_tx]
